# permissions for end users to edit harborprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborproject-editor-role
rules:
- apiGroups:
  - goharbor.k7s.dev
  resources:
  - harborprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.k7s.dev
  resources:
  - harborprojects/status
  verbs:
  - get
