# permissions for end users to view harborrobotaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborrobotaccount-viewer-role
rules:
- apiGroups:
  - goharbor.k7s.dev
  resources:
  - harborrobotaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goharbor.k7s.dev
  resources:
  - harborrobotaccounts/status
  verbs:
  - get
